name: main-eks

on:
  workflow_dispatch:
    inputs:
      action:
        type: choice
        description: Action
        default: create + delete
        options:
          - create
          - delete
          - create + delete
        required: true

env:
  MY_PASSWORD: ${{ secrets.MY_PASSWORD }}
  AWS_DEFAULT_REGION: eu-central-1
  AWS_GITHUB_OIDC_FEDERATED_ROLE_MAIN_EKS: ${{ secrets.AWS_GITHUB_OIDC_FEDERATED_ROLE_MAIN_EKS }}
  AWS_CONSOLE_ADMIN_ROLE_ARN_MAIN_EKS: ${{ secrets.AWS_CONSOLE_ADMIN_ROLE_ARN_MAIN_EKS }}
  AWS_USER_ROLE_ARN_MAIN_EKS: ${{ secrets.AWS_USER_ROLE_ARN_MAIN_EKS }}
  AWS_ACCOUNT_ID_ORG1: ${{ secrets.AWS_ACCOUNT_ID_ORG1 }}
  AWS_ACCESS_KEY_ID_ORG1: ${{ secrets.AWS_ACCESS_KEY_ID_ORG1 }}
  AWS_SECRET_ACCESS_KEY_ORG1: ${{ secrets.AWS_SECRET_ACCESS_KEY_ORG1 }}
  GH_TOKEN_FOR_UPDATING_THE_RANCHER_TOKEN_KEY: ${{ secrets.GH_TOKEN_FOR_UPDATING_THE_RANCHER_TOKEN_KEY }}

concurrency: main-eks

jobs:
  create-main-eks:
    name: "${{ github.event.inputs.action }} | main-eks"
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2

      - name: ðŸ’¡ðŸ”ª Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ env.AWS_GITHUB_OIDC_FEDERATED_ROLE_MAIN_EKS }}
          role-session-name: GitHubOidcFederatedRole
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: ðŸ’¡ Create EKS cluster + environment
        if: ${{ contains(github.event.inputs.action, 'create') }}
        run: |
          ./create-main-eks.sh

      - name: ðŸ’¡ Cluster access commands (kubeconfig)
        if: ${{ contains(github.event.inputs.action, 'create') }}
        run: |
          cat << \EOF
          https://rancher.main-eks.k8s.mylabs.dev/
          aws eks --region ${{ env.AWS_DEFAULT_REGION }} update-kubeconfig --name main-eks --kubeconfig /tmp/kubeconfig-main-eks.conf
          export KUBECONFIG="/tmp/kubeconfig-main-eks.conf"
          kubectl get nodes -o wide
          EOF

      - name: ðŸ”ª Delete EKS cluster + environment
        if: ${{ contains(github.event.inputs.action, 'delete') }}
        run: |
          ./delete-main-eks.sh
