name: mdbook-build

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/mdbook-build.yml
      - docs/**
      - package.json
      - package-lock.json
      - .spelling
      - .markdownlint.yml

permissions: read-all

jobs:
  mdbook-build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5

      - name: Install Node.js
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          # renovate: datasource=github-tags depName=nodejs/node versioning=node
          node-version: 20

      - name: Install markdown-spellcheck
        run: npm install -g markdown-spellcheck

      - name: Run mdspell
        run: find . -type f \( -name "*.md" ! -name "CHANGELOG.md" \) -print0 | xargs -0 --max-args=1 --verbose mdspell --ignore-numbers --ignore-acronyms --report --en-gb

      - uses: jontze/action-mdbook@83b871c38b000c7be415e9773f283786295e29dc # v3.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          use-linkcheck: true
          use-mermaid: false
          use-toc: true
          use-opengh: true

      - name: Build the document
        run: |
          mdbook build ./docs/
          touch ./docs/.nojekyll
          cp LICENSE ./docs/book/
          cp docs/src/README.md docs/book/README.md
          ln -s docs/book ${{ github.event.repository.name }}

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b # v5.0.0

      - name: Check broken links
        uses: ruzickap/action-my-broken-link-checker@bec36cf5736d969f1c5191b9fd2052df87675012 # v2.6.0
        with:
          url: ${{ steps.pages.outputs.base_url }}
          pages_path: .
          cmd_params: '--exclude=(${{ steps.pages.outputs.base_url }}/edit/main/docs/) --buffer-size=8192 --max-connections-per-host=5 --color=always --rate-limit=5 --header="User-Agent:Mozilla" --skip-tls-verification'

      - name: Deploy
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e # v4.0.0
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/book
          force_orphan: true
