name: shellcheck

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main
    paths:
      - "**.sh"
      - "**.md"
      - .github/workflows/shellcheck.yml

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Extract commands from markdown files
        run: |
          set -euxo pipefail
          echo '#!/usr/bin/env bash' > README.sh
          find . -name '*.md' -print0 | while IFS= read -r -d '' FILE ; do
            sed -n "/^\`\`\`\(bash\|shell\).*/,/^\`\`\`$/p" "${FILE}" \
            | \
            sed \
              -e 's/^```\(bash\|shell\).*//' \
              -e '/^```$/d' \
            >> README.sh
          done
          chmod a+x README.sh

      - name: Run the sh-checker
        uses: luizm/action-sh-checker@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHFMT_OPTS: --indent 2 --space-redirects
        with:
          sh_checker_comment: true
          sh_checker_exclude: "^scripts/flux-validate.sh"
